sudo: false # container base - quicker

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
# command to install dependencies
install: 
    - "python setup.py develop"
    - "pip install -r requirements.txt"
    - "pip install codecov"
# command to run tests
script: ./launch_test.sh
after_success:
    - codecov
